// Extended test with all 6 profiles
const fs = require('fs');
const { testProfileDirect, generateTestReport } = require('./direct-algorithm-test.js');

// All test profiles
const allTestProfiles = {
  technical: {
    name: "Technical/Engineering PhD",
    description: "Strong in quantitative skills, programming, analytical thinking",
    expectedTopCareers: ["data_scientist", "ai_ml_engineer", "software_engineering", "bioinformatics_scientist"],
    answers: {
      skills_technical_1: "a",
      skills_communication_1: "c", 
      skills_leadership_1: "a",
      skills_analytical_1: "a",
      skills_management_1: ["project_mgmt", "operations"],
      skills_specialized_1: ["computational", "finance"],
      problem_complexity_1: "a",
      technical_depth_1: "a",
      values_impact_1: ["intellectual", "commercial", "societal", "personal"],
      values_autonomy_1: 4,
      values_stability_1: "a",
      values_collaboration_1: "a", 
      values_creativity_1: "b",
      career_goals_1: "a",
      work_motivation_1: ["learning", "recognition", "compensation", "flexibility", "mission"],
      temperament_social_1: 2,
      temperament_detail_1: "a",
      temperament_structure_1: 3,
      temperament_pressure_1: "a",
      temperament_decision_1: "a",
      risk_tolerance_1: 3,
      programming_experience: 3,
      programming_languages: ["python", "r", "matlab", "cpp"],
      mathematics_background: 3,
      mathematical_areas: ["statistics", "linear_algebra", "calculus", "optimization"],
      data_analysis_experience: 4,
      data_tools_experience: ["python_data", "r_stats", "sql_databases", "cloud_platforms"],
      research_methodology: ["experimental_design", "computational_modeling", "literature_review"],
      technical_writing_experience: 3,
      business_finance_background: 1,
      lab_experience: 2,
      creative_design_experience: 1,
      clinical_experience: ["none_clinical"],
      phd_domain_1: "d"
    }
  },
  
  business: {
    name: "Business/Strategy PhD", 
    description: "Strong in leadership, communication, business strategy",
    expectedTopCareers: ["management_consultant", "product_manager", "venture_capital_analyst", "business_development_manager"],
    answers: {
      skills_technical_1: "d",
      skills_communication_1: "b",
      skills_leadership_1: "c", 
      skills_analytical_1: "d",
      skills_management_1: ["project_mgmt", "market_research", "policy", "risk_mgmt"],
      skills_specialized_1: ["finance", "user_research"],
      problem_complexity_1: "b",
      technical_depth_1: "c",
      values_impact_1: ["commercial", "societal", "intellectual", "personal"],
      values_autonomy_1: 3,
      values_stability_1: "b",
      values_collaboration_1: "c",
      values_creativity_1: "c", 
      career_goals_1: "b",
      work_motivation_1: ["recognition", "compensation", "learning", "mission", "flexibility"],
      temperament_social_1: 4,
      temperament_detail_1: "b",
      temperament_structure_1: 2,
      temperament_pressure_1: "b",
      temperament_decision_1: "c",
      risk_tolerance_1: 4,
      programming_experience: 1,
      programming_languages: ["python", "sql"],
      mathematics_background: 2,
      mathematical_areas: ["statistics"],
      data_analysis_experience: 2,
      data_tools_experience: ["excel", "spss_sas", "sql_databases"],
      research_methodology: ["survey_research", "literature_review"],
      technical_writing_experience: 2,
      business_finance_background: 2,
      lab_experience: 1,
      creative_design_experience: 0,
      clinical_experience: ["none_clinical"],
      phd_domain_1: "f"
    }
  },

  creative: {
    name: "Creative/Design PhD",
    description: "Strong in creativity, visual skills, user experience", 
    expectedTopCareers: ["ux_researcher", "science_illustrator", "science_communicator", "technical_writer"],
    answers: {
      skills_technical_1: "e",
      skills_communication_1: "e",
      skills_leadership_1: "d",
      skills_analytical_1: "e", 
      skills_management_1: ["project_mgmt", "market_research"],
      skills_specialized_1: ["user_research"],
      problem_complexity_1: "c",
      technical_depth_1: "d",
      values_impact_1: ["personal", "societal", "intellectual", "commercial"],
      values_autonomy_1: 4,
      values_stability_1: "a",
      values_collaboration_1: "b",
      values_creativity_1: "a",
      career_goals_1: "e",
      work_motivation_1: ["learning", "flexibility", "mission", "recognition", "compensation"],
      temperament_social_1: 3,
      temperament_detail_1: "d",
      temperament_structure_1: 4,
      temperament_pressure_1: "d",
      temperament_decision_1: "b",
      risk_tolerance_1: 4,
      programming_experience: 1,
      programming_languages: ["python", "javascript"],
      mathematics_background: 1,
      mathematical_areas: ["statistics"],
      data_analysis_experience: 1,
      data_tools_experience: ["excel", "python_data"],
      research_methodology: ["survey_research", "field_studies"],
      technical_writing_experience: 2,
      business_finance_background: 1,
      lab_experience: 1,
      creative_design_experience: 3,
      clinical_experience: ["none_clinical"],
      phd_domain_1: "f"
    }
  },

  research: {
    name: "Research/Academic PhD",
    description: "Strong in research methodology, writing, analysis",
    expectedTopCareers: ["research_scientist", "r_and_d_scientist", "scientific_writer", "technical_writer"],
    answers: {
      skills_technical_1: "c",
      skills_communication_1: "a",
      skills_leadership_1: "d",
      skills_analytical_1: "b",
      skills_management_1: ["fundraising", "policy"], 
      skills_specialized_1: ["epidemiology", "ip_law"],
      problem_complexity_1: "a",
      technical_depth_1: "a",
      values_impact_1: ["intellectual", "societal", "personal", "commercial"],
      values_autonomy_1: 4,
      values_stability_1: "c",
      values_collaboration_1: "a",
      values_creativity_1: "b",
      career_goals_1: "a",
      work_motivation_1: ["learning", "mission", "flexibility", "recognition", "compensation"],
      temperament_social_1: 2,
      temperament_detail_1: "a",
      temperament_structure_1: 2,
      temperament_pressure_1: "a",
      temperament_decision_1: "a",
      risk_tolerance_1: 2,
      programming_experience: 2,
      programming_languages: ["python", "r", "matlab"],
      mathematics_background: 3,
      mathematical_areas: ["statistics", "calculus", "numerical_methods"],
      data_analysis_experience: 3,
      data_tools_experience: ["r_stats", "python_data", "spss_sas"],
      research_methodology: ["experimental_design", "computational_modeling", "literature_review"],
      technical_writing_experience: 4,
      business_finance_background: 0,
      lab_experience: 4,
      creative_design_experience: 1,
      clinical_experience: ["none_clinical"],
      phd_domain_1: "a"
    }
  },

  healthcare: {
    name: "Healthcare/Biotech PhD",
    description: "Strong in life sciences, regulatory knowledge",
    expectedTopCareers: ["medical_science_liaison", "regulatory_affairs_specialist", "clinical_research_associate", "r_and_d_scientist"],
    answers: {
      skills_technical_1: "c",
      skills_communication_1: "d",
      skills_leadership_1: "b",
      skills_analytical_1: "a",
      skills_management_1: ["project_mgmt", "policy", "risk_mgmt"],
      skills_specialized_1: ["clinical", "epidemiology"],
      problem_complexity_1: "e",
      technical_depth_1: "b",
      values_impact_1: ["societal", "intellectual", "commercial", "personal"],
      values_autonomy_1: 3,
      values_stability_1: "e",
      values_collaboration_1: "d",
      values_creativity_1: "c",
      career_goals_1: "f",
      work_motivation_1: ["mission", "learning", "recognition", "flexibility", "compensation"],
      temperament_social_1: 4,
      temperament_detail_1: "a",
      temperament_structure_1: 1,
      temperament_pressure_1: "a", 
      temperament_decision_1: "a",
      risk_tolerance_1: 2,
      programming_experience: 1,
      programming_languages: ["r", "sql"],
      mathematics_background: 2,
      mathematical_areas: ["statistics"],
      data_analysis_experience: 2,
      data_tools_experience: ["r_stats", "spss_sas", "sql_databases"],
      research_methodology: ["experimental_design", "clinical_trials", "survey_research"],
      technical_writing_experience: 3,
      business_finance_background: 1,
      lab_experience: 3,
      creative_design_experience: 1,
      clinical_experience: ["clinical_trials", "medical_research", "regulatory_submission"],
      phd_domain_1: "a"
    }
  },

  finance: {
    name: "Finance/Economics PhD",
    description: "Strong in quantitative analysis, financial modeling",
    expectedTopCareers: ["quantitative_analyst", "financial_analyst", "venture_capital_analyst", "data_scientist"],
    answers: {
      skills_technical_1: "d",
      skills_communication_1: "c",
      skills_leadership_1: "c",
      skills_analytical_1: "a",
      skills_management_1: ["project_mgmt", "market_research", "risk_mgmt"],
      skills_specialized_1: ["finance"],
      problem_complexity_1: "b",
      technical_depth_1: "c",
      values_impact_1: ["commercial", "intellectual", "personal", "societal"],
      values_autonomy_1: 3,
      values_stability_1: "b",
      values_collaboration_1: "c",
      values_creativity_1: "c",
      career_goals_1: "b",
      work_motivation_1: ["compensation", "recognition", "learning", "flexibility", "mission"],
      temperament_social_1: 3,
      temperament_detail_1: "a",
      temperament_structure_1: 2,
      temperament_pressure_1: "b",
      temperament_decision_1: "a",
      risk_tolerance_1: 4,
      programming_experience: 3,
      programming_languages: ["python", "r", "sql"],
      mathematics_background: 3,
      mathematical_areas: ["statistics", "calculus", "optimization", "numerical_methods"],
      data_analysis_experience: 4,
      data_tools_experience: ["python_data", "r_stats", "excel", "sql_databases"],
      research_methodology: ["survey_research", "literature_review"],
      technical_writing_experience: 2,
      business_finance_background: 3,
      lab_experience: 0,
      creative_design_experience: 1,
      clinical_experience: ["none_clinical"],
      phd_domain_1: "d"
    }
  }
};

// Run extended tests
console.log('='.repeat(70));
console.log('COMPREHENSIVE CAREER QUIZ ALGORITHM TESTING - ALL PROFILES');
console.log('='.repeat(70));

const results = [];

for (const [profileKey, profileData] of Object.entries(allTestProfiles)) {
  const result = testProfileDirect(profileKey, profileData);
  results.push(result);
}

generateTestReport(results);